name: listify
description: "A modern shopping list app built with Clean Architecture and BLoC pattern."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  
  # State Management
  flutter_bloc: ^8.1.6
  equatable: ^2.0.7
  
  # Local Persistence
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  
  # Dependency Injection
  get_it: ^8.0.3
  
  # Functional Programming
  dartz: ^0.10.1
  
  # Utilities
  uuid: ^4.5.1
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  
  # Testing
  bloc_test: ^9.1.7
  mocktail: ^1.0.4
  
  # Code Generation
  hive_generator: ^2.0.1
  build_runner: ^2.4.14

flutter:
  uses-material-design: true
